[custom]

; Mini 纯简版，提取精简，简约轻修
; 节点筛选、重命名、排序请在订阅转换服务中设置

ruleset=🌐  本地直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🌐  本地直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list

ruleset=🛡️  广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=🛡️  广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list

ruleset=🌐  本地直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=🌐  本地直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
ruleset=🌐  本地直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list

ruleset=🚀  节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
ruleset=🚀  节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=🚀  节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyLite.list

ruleset=🌐  本地直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🌐  本地直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🌐  本地直连,[]GEOIP,CN

ruleset=🐟  漏网之鱼,[]FINAL

custom_proxy_group=🚀  节点选择`select`[]⚡  自动选择`.*
custom_proxy_group=⚡  自动选择`fallback`.*`http://cp.cloudflare.com/generate_204`200,,5000
custom_proxy_group=🌐  本地直连`select`[]DIRECT`[]🚀  节点选择
custom_proxy_group=🛡️  广告拦截`select`[]REJECT`[]DIRECT
custom_proxy_group=🐟  漏网之鱼`select`[]🚀  节点选择`[]DIRECT

enable_rule_generator=true
overwrite_original_rules=true
