[custom]

; Mini 精简版 + 微软直连 + 故障转移
; 节点筛选、重命名、排序请在订阅链接参数中处理

ruleset=🎯 直挂云帆济沧海,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 直挂云帆济沧海,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list

ruleset=⛔ 闲花乱絮不入门,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=⛔ 闲花乱絮不入门,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list

ruleset=🎯 直挂云帆济沧海,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=🎯 直挂云帆济沧海,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
ruleset=🎯 直挂云帆济沧海,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list

ruleset=🚀 星河万里择良路,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
ruleset=🚀 星河万里择良路,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=🚀 星河万里择良路,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyLite.list

ruleset=🎯 直挂云帆济沧海,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 直挂云帆济沧海,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🎯 直挂云帆济沧海,[]GEOIP,CN

ruleset=🐟 百川未尽终归海,[]FINAL

custom_proxy_group=🚀 星河万里择良路`select`[]🔄 路断云开别有天`.*
custom_proxy_group=🔄 路断云开别有天`fallback`.*`http://cp.cloudflare.com/generate_204`300,5000
custom_proxy_group=🎯 直挂云帆济沧海`select`[]DIRECT`[]🚀 星河万里择良路
custom_proxy_group=⛔ 闲花乱絮不入门`select`[]REJECT`[]DIRECT
custom_proxy_group=🐟 百川未尽终归海`select`[]🚀 星河万里择良路`[]🎯 直挂云帆济沧海`[]🔄 路断云开别有天

enable_rule_generator=true
overwrite_original_rules=true
